#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sguvs
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StikloNamaiDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVartotojas(Vartotojas instance);
    partial void UpdateVartotojas(Vartotojas instance);
    partial void DeleteVartotojas(Vartotojas instance);
    partial void InsertZaliava(Zaliava instance);
    partial void UpdateZaliava(Zaliava instance);
    partial void DeleteZaliava(Zaliava instance);
    partial void InsertUzsakyma(Uzsakyma instance);
    partial void UpdateUzsakyma(Uzsakyma instance);
    partial void DeleteUzsakyma(Uzsakyma instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::sguvs.Properties.Settings.Default.StikloNamaiDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Vartotojas> Vartotojas
		{
			get
			{
				return this.GetTable<Vartotojas>();
			}
		}
		
		public System.Data.Linq.Table<Zaliava> Zaliavas
		{
			get
			{
				return this.GetTable<Zaliava>();
			}
		}
		
		public System.Data.Linq.Table<Uzsakyma> Uzsakymas1
		{
			get
			{
				return this.GetTable<Uzsakyma>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vartotojas")]
	public partial class Vartotojas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_vartotojo;
		
		private string _vartotojo_ID;
		
		private string _slaptazodis1;
		
		private string _slaptazodis2;
		
		private string _pareigos;
		
		private string _vardas;
		
		private string _pavarde;
		
		private string _el_pastas;
		
		private int _telefonas;
		
		private string _adresas;
		
		private string _miestas;
		
		private bool _istrintas;
		
		private EntitySet<Uzsakyma> _Uzsakymas1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_vartotojoChanging(int value);
    partial void OnID_vartotojoChanged();
    partial void Onvartotojo_IDChanging(string value);
    partial void Onvartotojo_IDChanged();
    partial void Onslaptazodis1Changing(string value);
    partial void Onslaptazodis1Changed();
    partial void Onslaptazodis2Changing(string value);
    partial void Onslaptazodis2Changed();
    partial void OnpareigosChanging(string value);
    partial void OnpareigosChanged();
    partial void OnvardasChanging(string value);
    partial void OnvardasChanged();
    partial void OnpavardeChanging(string value);
    partial void OnpavardeChanged();
    partial void Onel_pastasChanging(string value);
    partial void Onel_pastasChanged();
    partial void OntelefonasChanging(int value);
    partial void OntelefonasChanged();
    partial void OnadresasChanging(string value);
    partial void OnadresasChanged();
    partial void OnmiestasChanging(string value);
    partial void OnmiestasChanged();
    partial void OnistrintasChanging(bool value);
    partial void OnistrintasChanged();
    #endregion
		
		public Vartotojas()
		{
			this._Uzsakymas1 = new EntitySet<Uzsakyma>(new Action<Uzsakyma>(this.attach_Uzsakymas1), new Action<Uzsakyma>(this.detach_Uzsakymas1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_vartotojo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_vartotojo
		{
			get
			{
				return this._ID_vartotojo;
			}
			set
			{
				if ((this._ID_vartotojo != value))
				{
					this.OnID_vartotojoChanging(value);
					this.SendPropertyChanging();
					this._ID_vartotojo = value;
					this.SendPropertyChanged("ID_vartotojo");
					this.OnID_vartotojoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vartotojo_ID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string vartotojo_ID
		{
			get
			{
				return this._vartotojo_ID;
			}
			set
			{
				if ((this._vartotojo_ID != value))
				{
					this.Onvartotojo_IDChanging(value);
					this.SendPropertyChanging();
					this._vartotojo_ID = value;
					this.SendPropertyChanged("vartotojo_ID");
					this.Onvartotojo_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slaptazodis1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string slaptazodis1
		{
			get
			{
				return this._slaptazodis1;
			}
			set
			{
				if ((this._slaptazodis1 != value))
				{
					this.Onslaptazodis1Changing(value);
					this.SendPropertyChanging();
					this._slaptazodis1 = value;
					this.SendPropertyChanged("slaptazodis1");
					this.Onslaptazodis1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slaptazodis2", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string slaptazodis2
		{
			get
			{
				return this._slaptazodis2;
			}
			set
			{
				if ((this._slaptazodis2 != value))
				{
					this.Onslaptazodis2Changing(value);
					this.SendPropertyChanging();
					this._slaptazodis2 = value;
					this.SendPropertyChanged("slaptazodis2");
					this.Onslaptazodis2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pareigos", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string pareigos
		{
			get
			{
				return this._pareigos;
			}
			set
			{
				if ((this._pareigos != value))
				{
					this.OnpareigosChanging(value);
					this.SendPropertyChanging();
					this._pareigos = value;
					this.SendPropertyChanged("pareigos");
					this.OnpareigosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vardas", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string vardas
		{
			get
			{
				return this._vardas;
			}
			set
			{
				if ((this._vardas != value))
				{
					this.OnvardasChanging(value);
					this.SendPropertyChanging();
					this._vardas = value;
					this.SendPropertyChanged("vardas");
					this.OnvardasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pavarde", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string pavarde
		{
			get
			{
				return this._pavarde;
			}
			set
			{
				if ((this._pavarde != value))
				{
					this.OnpavardeChanging(value);
					this.SendPropertyChanging();
					this._pavarde = value;
					this.SendPropertyChanged("pavarde");
					this.OnpavardeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_el_pastas", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string el_pastas
		{
			get
			{
				return this._el_pastas;
			}
			set
			{
				if ((this._el_pastas != value))
				{
					this.Onel_pastasChanging(value);
					this.SendPropertyChanging();
					this._el_pastas = value;
					this.SendPropertyChanged("el_pastas");
					this.Onel_pastasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefonas", DbType="Int NOT NULL")]
		public int telefonas
		{
			get
			{
				return this._telefonas;
			}
			set
			{
				if ((this._telefonas != value))
				{
					this.OntelefonasChanging(value);
					this.SendPropertyChanging();
					this._telefonas = value;
					this.SendPropertyChanged("telefonas");
					this.OntelefonasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresas", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string adresas
		{
			get
			{
				return this._adresas;
			}
			set
			{
				if ((this._adresas != value))
				{
					this.OnadresasChanging(value);
					this.SendPropertyChanging();
					this._adresas = value;
					this.SendPropertyChanged("adresas");
					this.OnadresasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miestas", DbType="VarChar(50)")]
		public string miestas
		{
			get
			{
				return this._miestas;
			}
			set
			{
				if ((this._miestas != value))
				{
					this.OnmiestasChanging(value);
					this.SendPropertyChanging();
					this._miestas = value;
					this.SendPropertyChanged("miestas");
					this.OnmiestasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_istrintas", DbType="Bit NOT NULL")]
		public bool istrintas
		{
			get
			{
				return this._istrintas;
			}
			set
			{
				if ((this._istrintas != value))
				{
					this.OnistrintasChanging(value);
					this.SendPropertyChanging();
					this._istrintas = value;
					this.SendPropertyChanged("istrintas");
					this.OnistrintasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vartotojas_Uzsakyma", Storage="_Uzsakymas1", ThisKey="ID_vartotojo", OtherKey="ID_vartotojo")]
		public EntitySet<Uzsakyma> Uzsakymas1
		{
			get
			{
				return this._Uzsakymas1;
			}
			set
			{
				this._Uzsakymas1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Uzsakymas1(Uzsakyma entity)
		{
			this.SendPropertyChanging();
			entity.Vartotojas = this;
		}
		
		private void detach_Uzsakymas1(Uzsakyma entity)
		{
			this.SendPropertyChanging();
			entity.Vartotojas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zaliava")]
	public partial class Zaliava : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_zaliava;
		
		private string _zaliava_ID;
		
		private double _storis;
		
		private double _plotis;
		
		private int _kiekis;
		
		private double _turimas_kiekis;
		
		private double _kaina;
		
		private bool _istrintas;
		
		private EntityRef<Uzsakyma> _Uzsakyma;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_zaliavaChanging(int value);
    partial void OnID_zaliavaChanged();
    partial void Onzaliava_IDChanging(string value);
    partial void Onzaliava_IDChanged();
    partial void OnstorisChanging(double value);
    partial void OnstorisChanged();
    partial void OnplotisChanging(double value);
    partial void OnplotisChanged();
    partial void OnkiekisChanging(int value);
    partial void OnkiekisChanged();
    partial void Onturimas_kiekisChanging(double value);
    partial void Onturimas_kiekisChanged();
    partial void OnkainaChanging(double value);
    partial void OnkainaChanged();
    partial void OnistrintasChanging(bool value);
    partial void OnistrintasChanged();
    #endregion
		
		public Zaliava()
		{
			this._Uzsakyma = default(EntityRef<Uzsakyma>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_zaliava", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_zaliava
		{
			get
			{
				return this._ID_zaliava;
			}
			set
			{
				if ((this._ID_zaliava != value))
				{
					if (this._Uzsakyma.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_zaliavaChanging(value);
					this.SendPropertyChanging();
					this._ID_zaliava = value;
					this.SendPropertyChanged("ID_zaliava");
					this.OnID_zaliavaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zaliava_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string zaliava_ID
		{
			get
			{
				return this._zaliava_ID;
			}
			set
			{
				if ((this._zaliava_ID != value))
				{
					this.Onzaliava_IDChanging(value);
					this.SendPropertyChanging();
					this._zaliava_ID = value;
					this.SendPropertyChanged("zaliava_ID");
					this.Onzaliava_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_storis", DbType="Float NOT NULL")]
		public double storis
		{
			get
			{
				return this._storis;
			}
			set
			{
				if ((this._storis != value))
				{
					this.OnstorisChanging(value);
					this.SendPropertyChanging();
					this._storis = value;
					this.SendPropertyChanged("storis");
					this.OnstorisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plotis", DbType="Float NOT NULL")]
		public double plotis
		{
			get
			{
				return this._plotis;
			}
			set
			{
				if ((this._plotis != value))
				{
					this.OnplotisChanging(value);
					this.SendPropertyChanging();
					this._plotis = value;
					this.SendPropertyChanged("plotis");
					this.OnplotisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kiekis", DbType="Int NOT NULL")]
		public int kiekis
		{
			get
			{
				return this._kiekis;
			}
			set
			{
				if ((this._kiekis != value))
				{
					this.OnkiekisChanging(value);
					this.SendPropertyChanging();
					this._kiekis = value;
					this.SendPropertyChanged("kiekis");
					this.OnkiekisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turimas_kiekis", DbType="Float NOT NULL")]
		public double turimas_kiekis
		{
			get
			{
				return this._turimas_kiekis;
			}
			set
			{
				if ((this._turimas_kiekis != value))
				{
					this.Onturimas_kiekisChanging(value);
					this.SendPropertyChanging();
					this._turimas_kiekis = value;
					this.SendPropertyChanged("turimas_kiekis");
					this.Onturimas_kiekisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kaina", DbType="Float NOT NULL")]
		public double kaina
		{
			get
			{
				return this._kaina;
			}
			set
			{
				if ((this._kaina != value))
				{
					this.OnkainaChanging(value);
					this.SendPropertyChanging();
					this._kaina = value;
					this.SendPropertyChanged("kaina");
					this.OnkainaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_istrintas", DbType="Bit NOT NULL")]
		public bool istrintas
		{
			get
			{
				return this._istrintas;
			}
			set
			{
				if ((this._istrintas != value))
				{
					this.OnistrintasChanging(value);
					this.SendPropertyChanging();
					this._istrintas = value;
					this.SendPropertyChanged("istrintas");
					this.OnistrintasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uzsakyma_Zaliava", Storage="_Uzsakyma", ThisKey="ID_zaliava", OtherKey="ID_uzsakymo", IsForeignKey=true)]
		public Uzsakyma Uzsakyma
		{
			get
			{
				return this._Uzsakyma.Entity;
			}
			set
			{
				Uzsakyma previousValue = this._Uzsakyma.Entity;
				if (((previousValue != value) 
							|| (this._Uzsakyma.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Uzsakyma.Entity = null;
						previousValue.Zaliava = null;
					}
					this._Uzsakyma.Entity = value;
					if ((value != null))
					{
						value.Zaliava = this;
						this._ID_zaliava = value.ID_uzsakymo;
					}
					else
					{
						this._ID_zaliava = default(int);
					}
					this.SendPropertyChanged("Uzsakyma");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uzsakymas")]
	public partial class Uzsakyma : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_uzsakymo;
		
		private int _ID_vartotojo;
		
		private string _uzsakymo_ID;
		
		private string _zaliava_ID;
		
		private int _ilgis;
		
		private int _plotis;
		
		private int _kiekis;
		
		private double _plotas;
		
		private double _kaina;
		
		private bool _statusas;
		
		private EntityRef<Zaliava> _Zaliava;
		
		private EntityRef<Vartotojas> _Vartotojas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_uzsakymoChanging(int value);
    partial void OnID_uzsakymoChanged();
    partial void OnID_vartotojoChanging(int value);
    partial void OnID_vartotojoChanged();
    partial void Onuzsakymo_IDChanging(string value);
    partial void Onuzsakymo_IDChanged();
    partial void Onzaliava_IDChanging(string value);
    partial void Onzaliava_IDChanged();
    partial void OnilgisChanging(int value);
    partial void OnilgisChanged();
    partial void OnplotisChanging(int value);
    partial void OnplotisChanged();
    partial void OnkiekisChanging(int value);
    partial void OnkiekisChanged();
    partial void OnplotasChanging(double value);
    partial void OnplotasChanged();
    partial void OnkainaChanging(double value);
    partial void OnkainaChanged();
    partial void OnstatusasChanging(bool value);
    partial void OnstatusasChanged();
    #endregion
		
		public Uzsakyma()
		{
			this._Zaliava = default(EntityRef<Zaliava>);
			this._Vartotojas = default(EntityRef<Vartotojas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_uzsakymo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_uzsakymo
		{
			get
			{
				return this._ID_uzsakymo;
			}
			set
			{
				if ((this._ID_uzsakymo != value))
				{
					this.OnID_uzsakymoChanging(value);
					this.SendPropertyChanging();
					this._ID_uzsakymo = value;
					this.SendPropertyChanged("ID_uzsakymo");
					this.OnID_uzsakymoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_vartotojo", DbType="Int NOT NULL")]
		public int ID_vartotojo
		{
			get
			{
				return this._ID_vartotojo;
			}
			set
			{
				if ((this._ID_vartotojo != value))
				{
					if (this._Vartotojas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_vartotojoChanging(value);
					this.SendPropertyChanging();
					this._ID_vartotojo = value;
					this.SendPropertyChanged("ID_vartotojo");
					this.OnID_vartotojoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uzsakymo_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string uzsakymo_ID
		{
			get
			{
				return this._uzsakymo_ID;
			}
			set
			{
				if ((this._uzsakymo_ID != value))
				{
					this.Onuzsakymo_IDChanging(value);
					this.SendPropertyChanging();
					this._uzsakymo_ID = value;
					this.SendPropertyChanged("uzsakymo_ID");
					this.Onuzsakymo_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zaliava_ID", DbType="VarChar(50)")]
		public string zaliava_ID
		{
			get
			{
				return this._zaliava_ID;
			}
			set
			{
				if ((this._zaliava_ID != value))
				{
					this.Onzaliava_IDChanging(value);
					this.SendPropertyChanging();
					this._zaliava_ID = value;
					this.SendPropertyChanged("zaliava_ID");
					this.Onzaliava_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilgis", DbType="Int NOT NULL")]
		public int ilgis
		{
			get
			{
				return this._ilgis;
			}
			set
			{
				if ((this._ilgis != value))
				{
					this.OnilgisChanging(value);
					this.SendPropertyChanging();
					this._ilgis = value;
					this.SendPropertyChanged("ilgis");
					this.OnilgisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plotis", DbType="Int NOT NULL")]
		public int plotis
		{
			get
			{
				return this._plotis;
			}
			set
			{
				if ((this._plotis != value))
				{
					this.OnplotisChanging(value);
					this.SendPropertyChanging();
					this._plotis = value;
					this.SendPropertyChanged("plotis");
					this.OnplotisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kiekis", DbType="Int NOT NULL")]
		public int kiekis
		{
			get
			{
				return this._kiekis;
			}
			set
			{
				if ((this._kiekis != value))
				{
					this.OnkiekisChanging(value);
					this.SendPropertyChanging();
					this._kiekis = value;
					this.SendPropertyChanged("kiekis");
					this.OnkiekisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plotas", DbType="Float NOT NULL")]
		public double plotas
		{
			get
			{
				return this._plotas;
			}
			set
			{
				if ((this._plotas != value))
				{
					this.OnplotasChanging(value);
					this.SendPropertyChanging();
					this._plotas = value;
					this.SendPropertyChanged("plotas");
					this.OnplotasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kaina", DbType="Float NOT NULL")]
		public double kaina
		{
			get
			{
				return this._kaina;
			}
			set
			{
				if ((this._kaina != value))
				{
					this.OnkainaChanging(value);
					this.SendPropertyChanging();
					this._kaina = value;
					this.SendPropertyChanged("kaina");
					this.OnkainaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusas", DbType="Bit NOT NULL")]
		public bool statusas
		{
			get
			{
				return this._statusas;
			}
			set
			{
				if ((this._statusas != value))
				{
					this.OnstatusasChanging(value);
					this.SendPropertyChanging();
					this._statusas = value;
					this.SendPropertyChanged("statusas");
					this.OnstatusasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uzsakyma_Zaliava", Storage="_Zaliava", ThisKey="ID_uzsakymo", OtherKey="ID_zaliava", IsUnique=true, IsForeignKey=false)]
		public Zaliava Zaliava
		{
			get
			{
				return this._Zaliava.Entity;
			}
			set
			{
				Zaliava previousValue = this._Zaliava.Entity;
				if (((previousValue != value) 
							|| (this._Zaliava.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Zaliava.Entity = null;
						previousValue.Uzsakyma = null;
					}
					this._Zaliava.Entity = value;
					if ((value != null))
					{
						value.Uzsakyma = this;
					}
					this.SendPropertyChanged("Zaliava");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vartotojas_Uzsakyma", Storage="_Vartotojas", ThisKey="ID_vartotojo", OtherKey="ID_vartotojo", IsForeignKey=true)]
		public Vartotojas Vartotojas
		{
			get
			{
				return this._Vartotojas.Entity;
			}
			set
			{
				Vartotojas previousValue = this._Vartotojas.Entity;
				if (((previousValue != value) 
							|| (this._Vartotojas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vartotojas.Entity = null;
						previousValue.Uzsakymas1.Remove(this);
					}
					this._Vartotojas.Entity = value;
					if ((value != null))
					{
						value.Uzsakymas1.Add(this);
						this._ID_vartotojo = value.ID_vartotojo;
					}
					else
					{
						this._ID_vartotojo = default(int);
					}
					this.SendPropertyChanged("Vartotojas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
